class InvalidPinError(Exception):pass
class AccountAlreadyExistsError(Exception):pass
class InsufficientError(Exception):pass
class MobileNumberError(Exception):pass
class EmailError(Exception):pass
class AccountNotFoundError(Exception):pass
class SelfTransferError(Exception):pass
class InactiveAccountError(Exception):pass
class InvalidAadhaarNumberError(Exception):pass
class EmptyInputError(Exception):pass
class NegativeNumberError(Exception):pass
class ReceiverNotFoundError(Exception):pass
class TransactionError(Exception):pass
class DataNotFoundError(Exception):pass
class NoDataFoundError(Exception):pass
class AlreadyClosedError(Exception):pass
class PendingBalanceError(Exception):pass
class InvalidIFSCError(Exception):pass
class AuthorizationError(Exception):pass
class NameError(Exception):pass
class AadharCardError(Exception):pass
class BalanceError(Exception):pass
class SavcurError(Exception):pass
class InvalidDenominationError(Exception):pass
class MobileNumberNotMatchError(Exception):pass
class MinimumBalanceError(Exception):pass
class AmountError(Exception):pass
class AadhaarCardError(Exception):pass
class AccountsameError(Exception):pass
class BalanceLessthanError(Exception):pass